<?php

/**
 * @file
 * Contains azgrad_drupal_webform_components.module.
 */

/**
 * Get a simple list of academic plans.
 */
function azgrad_drupal_webform_components_webform_options_azgrad_all_graduate_plans_alter(
  array &$options,
  array &$element,
) {
  azgrad_drupal_webform_components_get_options(
    $options,
    'https://cloud.grad.arizona.edu/data/directory/simpleplans.json',
    'azgrad_all_graduate_plans',
    function (array $response) {
      $programs = [];
      foreach ($response as $next_plan) {
        $programs[$next_plan['gcAcadPlan']] = $next_plan['description'];
      }
      asort($programs);

      return $programs;
    }
  );
}

/**
 * Get a list of Accelerated Master's plans.
 */
function azgrad_drupal_webform_components_webform_options_azgrad_accelerated_masters_plans_alter(
  array &$options,
  array &$element,
) {
  azgrad_drupal_webform_components_get_options(
    $options,
    'https://cloud.grad.arizona.edu/data/directory/simpleplans.json',
    'azgrad_accelerated_masters_plans',
    function (array $response) {
      $programs = [];
      foreach ($response as $next_plan) {
        $is_amp = substr($next_plan['gcAcadPlan'], -3) == 'AMP';
        if ($is_amp) {
          $programs[$next_plan['gcAcadPlan']] = $next_plan['description'];
        }
      }
      asort($programs);

      return $programs;
    }
  );
}

/**
 * Get a list of certificate plans.
 */
function azgrad_drupal_webform_components_webform_options_azgrad_certificate_plans_alter(
  array &$options,
  array &$element,
) {
  azgrad_drupal_webform_components_get_options(
    $options,
    'https://cloud.grad.arizona.edu/data/directory/simpleplans.json',
    'azgrad_certificate_plans',
    function (array $response) {
      $programs = [];
      foreach ($response as $next_plan) {
        if ($next_plan['degree'] == 'CERTG') {
          $programs[$next_plan['gcAcadPlan']] = $next_plan['description'];
        }
      }
      asort($programs);

      return $programs;
    }
  );
}

/**
 * Get a list of degree-seeking plans - include AMPs.
 */
function azgrad_drupal_webform_components_webform_options_azgrad_degree_seeking_plans_alter(
  array &$options,
  array &$element,
) {
  azgrad_drupal_webform_components_get_options(
    $options,
    'https://cloud.grad.arizona.edu/data/directory/simpleplans.json',
    'azgrad_degree_seeking_plans',
    function (array $response) {
      $programs = [];
      foreach ($response as $next_plan) {
        $is_degree = $next_plan['degree'] !== 'CERTG'
          && substr($next_plan['acadPlan'], -4) !== 'MING'
          && $next_plan['acadPlan'] !== 'NDSNDG';
        if ($is_degree) {
          $programs[$next_plan['gcAcadPlan']] = $next_plan['description'];
        }
      }
      asort($programs);

      return $programs;
    }
  );
}

/**
 * Get a list of degree-seeking plans - not including AMPs.
 */
function azgrad_drupal_webform_components_webform_options_azgrad_degree_seeking_non_amps_alter(
  array &$options,
  array &$element,
) {
  azgrad_drupal_webform_components_get_options(
    $options,
    'https://cloud.grad.arizona.edu/data/directory/simpleplans.json',
    'azgrad_degree_seeking_non_amps',
    function (array $response) {
      $programs = [];
      foreach ($response as $next_plan) {
        $is_degree = $next_plan['degree'] !== 'CERTG'
          && substr($next_plan['acadPlan'], -4) !== 'MING'
          && substr($next_plan['gcAcadPlan'], -3) !== 'AMP'
          && $next_plan['acadPlan'] !== 'NDSNDG';
        if ($is_degree) {
          $programs[$next_plan['gcAcadPlan']] = $next_plan['description'];
        }
      }
      asort($programs);

      return $programs;
    }
  );
}

/**
 * Get a list of doctoral minors.
 */
function azgrad_drupal_webform_components_webform_options_azgrad_doctoral_minors_alter(
  array &$options,
  array &$element,
) {
  azgrad_drupal_webform_components_get_options(
    $options,
    'https://cloud.grad.arizona.edu/data/directory/simpleplans.json',
    'azgrad_doctoral_minors',
    function (array $response) {
      $programs = [];
      foreach ($response as $next_plan) {
        $is_minor = substr($next_plan['acadPlan'], -4) == 'MING';
        if ($is_minor) {
          $programs[$next_plan['gcAcadPlan']] = $next_plan['description'];
        }
      }
      asort($programs);

      return $programs;
    }
  );
}

/**
 * Get a list of doctoral plans.
 */
function azgrad_drupal_webform_components_webform_options_azgrad_doctoral_plans_alter(
  array &$options,
  array &$element,
) {
  azgrad_drupal_webform_components_get_options(
    $options,
    'https://cloud.grad.arizona.edu/data/directory/simpleplans.json',
    'azgrad_doctoral_plans',
    function (array $response) {
      $programs = [];
      foreach ($response as $next_plan) {
        if ($next_plan['degreeType'] == 'Doctorate') {
          $programs[$next_plan['gcAcadPlan']] = $next_plan['description'];
        }
      }
      asort($programs);

      return $programs;
    }
  );
}

/**
 * Get a list of Master's plans.
 */
function azgrad_drupal_webform_components_webform_options_azgrad_masters_plans_alter(
  array &$options,
  array &$element,
) {
  azgrad_drupal_webform_components_get_options(
    $options,
    'https://cloud.grad.arizona.edu/data/directory/simpleplans.json',
    'azgrad_masters_plans',
    function (array $response) {
      $programs = [];
      foreach ($response as $next_plan) {
        if ($next_plan['degreeType'] == 'Masters') {
          $programs[$next_plan['gcAcadPlan']] = $next_plan['description'];
        }
      }
      asort($programs);

      return $programs;
    }
  );
}

/**
 * Get a list of Master's without AMPs.
 */
function azgrad_drupal_webform_components_webform_options_azgrad_masters_non_amps_alter(
  array &$options,
  array &$element,
) {
  azgrad_drupal_webform_components_get_options(
    $options,
    'https://cloud.grad.arizona.edu/data/directory/simpleplans.json',
    'azgrad_masters_non_amps',
    function (array $response) {
      $programs = [];
      foreach ($response as $next_plan) {
        $is_nonamp = $next_plan['degreeType'] == 'Masters'
          && substr($next_plan['gcAcadPlan'], -3) !== 'AMP';
        if ($is_nonamp) {
          $programs[$next_plan['gcAcadPlan']] = $next_plan['description'];
        }
      }
      asort($programs);

      return $programs;
    }
  );
}

/**
 * Get a list of all terms.
 */
function azgrad_drupal_webform_components_webform_options_azgrad_terms_all_alter(
  array &$options,
  array &$element,
) {
  azgrad_drupal_webform_components_get_options(
    $options,
    'https://cloud.grad.arizona.edu/data/directory/terms.json',
    'azgrad_terms_all',
    function (array $response) {
      $terms = [];
      foreach ($response as $next_term) {
        if (!empty($next_term['term']) && $next_term['term'] != '1011') {
          $terms[$next_term['term']] = $next_term['descr'];
        }
      }
      ksort($terms, SORT_NUMERIC);

      return $terms;
    }
  );
}

/**
 * Get a list of current and future terms.
 */
function azgrad_drupal_webform_components_webform_options_azgrad_terms_current_future_alter(
  array &$options,
  array &$element,
) {
  azgrad_drupal_webform_components_get_options(
    $options,
    'https://cloud.grad.arizona.edu/data/directory/terms.json',
    'azgrad_terms_current_future',
    function (array $response) {
      $terms = [];
      $now = time();

      foreach ($response as $next_term) {
        $term_end = strtotime($next_term['endDate']);
        if (!empty($next_term['term']) && ($term_end >= $now)) {
          $terms[$next_term['term']] = $next_term['descr'];
        }
      }
      ksort($terms, SORT_NUMERIC);

      return $terms;
    }
  );
}

/**
 * Get a list of campuses.
 */
function azgrad_drupal_webform_components_webform_options_azgrad_campuses_alter(
  array &$options,
  array &$element,
) {
  azgrad_drupal_webform_components_get_options(
    $options,
    'https://cloud.grad.arizona.edu/data/directory/campuses.json',
    'azgrad_campuses',
    function (array $response) {
      $campuses = [];
      foreach ($response as $next_campus) {
        if (!empty($next_campus['campus']) && !empty($next_campus['descr'])) {
          $campuses[$next_campus['campus']] = $next_campus['descr'];
        }
      }
      asort($campuses);

      return $campuses;
    }
  );
}

/**
 * Get a list of campuses locations.
 */
function azgrad_drupal_webform_components_webform_options_azgrad_locations_alter(
  array &$options,
  array &$element,
) {
  azgrad_drupal_webform_components_get_options(
    $options,
    'https://cloud.grad.arizona.edu/data/directory/locations.json',
    'azgrad_locations',
    function (array $response) {
      $locations = [];
      foreach ($response as $next_location) {
        if (!empty($next_location['location']) && !empty($next_location['descr'])) {
          $locations[$next_location['location']] = $next_location['descr'];
        }
      }
      asort($locations);

      return $locations;
    }
  );
}

/**
 * Query the remote data endpoint.
 */
function azgrad_drupal_webform_components_get_options(
  array &$options,
  string $url,
  string $cache_key,
  Closure $filter_callback,
) {
  // Load cached options.
  if ($cache = \Drupal::cache()->get($cache_key)) {
    $options = $cache->data;

    return;
  }

  $response = json_decode(file_get_contents($url), TRUE);

  if (!$response) {
    $response = [];
  }

  $filtered_response = $filter_callback($response);
  $options = $filtered_response;
  \Drupal::cache()->set($cache_key, $options);
}
